### ISSUE TITLE
Add a link to your p5.js sketch

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [sara-desing/creativeartshow#1]
I know this sounds like I am sending you on a wild goose chase but make a link to your p5.js sketch in your readme.md so that everything is connected and easier to get comfortable with workflow:
1. testing
2. editting
3. designing
4. updating

Working through this process will allow you to get more comfortable making edits and changes with more confidence.

**Comment by sara-desing** [comment]
It's fine, I don't mind and I have added the link to my p5.js sketch to my
README.md.

**Comment by Ma1hT3ach3r** [comment]
Once you finish an issue, make sure you close it.

Also you will want to write your own issues, like the original one in the email, using an issue.

This will allow you(and me) to track what you have done and how you have addressed each issue.

Keep up the good work Sara!
